name: 官報RSS生成

on:
  schedule:
    - cron: "35 23 * * *" # JST 8:35 に実行
  workflow_dispatch:

jobs:
  fetch-kanpo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 官報チェック(DL無し)
        id: fetch-kanpo-step
        uses: testkun08080/action-kanpo@main
        with:
          dlpdf: "false"
    outputs:
      kanpo_found: ${{ steps.fetch-kanpo-step.outputs.kanpo_found }}
      pdf_infos: ${{ steps.fetch-kanpo-step.outputs.pdf_infos }}
      toc_infos: ${{ steps.fetch-kanpo-step.outputs.toc_infos }}

  show-fetch-kanpo-results:
    needs: fetch-kanpo
    runs-on: ubuntu-latest
    steps:
      - name: 結果を表示
        run: |
          echo "官報取得成功 or 失敗: ${{ needs.fetch-kanpo.outputs.kanpo_found }}"
          echo "取得PDF情報: ${{ needs.fetch-kanpo.outputs.pdf_infos }}"
          echo "取得目次情報: ${{ needs.fetch-kanpo.outputs.toc_infos }}"

  generate-rss-kanpo:
    needs: fetch-kanpo
    if: needs.fetch-kanpo.outputs.kanpo_found == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests python-dateutil

      - name: Generate RSS feed
        run: |
          python generate_rss.py "${{ needs.fetch-kanpo.outputs.pdf_infos }}"

      - name: Upload RSS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rss-files
          path: |
            feed.xml
            rss_data.json

  generate-toc-rss-kanpo:
    needs: [fetch-kanpo, generate-rss-kanpo]
    runs-on: ubuntu-latest
    if: needs.fetch-kanpo.outputs.kanpo_found == 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests python-dateutil

      - name: Generate TOC RSS feed
        run: |
          python generate_toc_rss.py "${{ needs.fetch-kanpo.outputs.toc_infos }}"

      - name: Upload TOC RSS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: toc-rss-files
          path: |
            feed_toc.xml
            rss_toc_data.json

  commit-all:
    needs: [generate-rss-kanpo, generate-toc-rss-kanpo]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download RSS artifacts
        uses: actions/download-artifact@v4
        with:
          name: rss-files
          path: .

      - name: Download TOC RSS artifacts
        uses: actions/download-artifact@v4
        with:
          name: toc-rss-files
          path: .

      - name: Git config and pull
        run: |
          git config --global user.name "testkun08080"
          git config --global user.email "154046906+testkun08080@users.noreply.github.com"
          git pull origin main --rebase || true

      - name: Commit and Push all RSS updates
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "RSS自動更新"

  # tweet:
  #   name: ツイート送信
  #   if: needs.fetch-kanpo.outputs.kanpo_found == 'true'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: noweh/post-tweet-v2-action@v1.0
  #       with:
  #         message: "今日の官報！ #官報"
  #         consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
  #         consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
  #         access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
  #         access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
